### ISSUE TITLE
How to generate public key from private key?

### ISSUE THREAD

**Issue by tearsofphoenix** [NTRUOpenSourceProject/NTRUEncrypt#12]
Does the library have any api to create public key from a private key? Or maybe use the same parameters to regenerate private key & public key pair?

**Comment by wwhyte-si** [comment]
Hi tearsofphoenix, 

The library as written supports generating a fresh keypair every time rather than regenerating from a seed. If you want to regenerate from a seed, you'll need to write your own entropy function as defined in ntru_crypto_drbg.h -- the README describes how to do this -- and hardwire the seed into that entropy function.
